src/Entity/Notes.php
<?php

namespace App\Entity;

use App\Repository\NotesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NotesRepository::class)]
class Notes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column]
    private ?int $user_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): static
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }
}

templates/pages/post_it_notes/mes_notes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Waou - Liste de mes notes
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
{% endblock %}
{% block body %}
	<section style="margin-top: 15%" class="container-list-calendrier element-to-scroll">
		<div class="container-list row">
			<a class="button-add" href="{{ path('app_lst_post_it_notes_add') }}">Ajouter</a>
			<div class="container-texte-exemple">
				<h3>Dans cette rubrique indiquez vos notes.<br>Peut importe la taille ou la longueur de vos notes.</h3>
			</div>
			<table class="table table-striped">
				<thead>
					<tr class="three_columns">
						<th scope="col" class="intitule" style="width: 30%;">Titre</th>
						<th scope="col">Date de création</th>
						<th scope="col">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for entry in lstNotes %}
						<tr class="three_columns">
							<th scope="row">{{ entry.titre }}</th>
							<td>{{ entry.dateCreation|date('d-m-Y') }}</td>
							<td>
								<a class="delete-button" href="{{ path('app_delete_note', {'id' : entry.id}) }}" onclick="return confirm('Voulez-vous vraiment supprimer cette activite professionnelle ?')">
									<img style="width: 15%;" src="{{ asset('img/icon-croix.png') }}" alt="Supprimer">
								</a>
								<a href="{{ path('app_lst_post_it_notes_modify', {'id' : entry.id}) }}">
									<img style="width: 10%;" src="{{ asset('img/icon-modifier.png') }}" alt="modifier">
								</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</section>
{% endblock %}

templates/pages/post_it_notes/notes_add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Waou -
	{{ (app.request.get('_route') == 'app_lst_post_it_notes_add' ? 'Ajouter' : 'Modifier') }}
	une note
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
	{{ encore_entry_link_tags('login') }}
{% endblock %}
{% block body %}
	{{ form_start(form_notes, {'attr': {'class': 'element-to-scroll mb-5'}}) }}
	<div class="row container-principal-form">
		<div class="col-8 mx-auto container-intro">
			<div class="col-form" style="width: 100%;">
				<h1>{{ (app.request.get('_route') == 'app_lst_post_it_notes_add' ? 'Créer' : 'Modifier') }}
					une note</h1>
			</div>
			<div class="col-form">
				{{ form_label(form_notes.titre) }}
				{{ form_widget(form_notes.titre) }}
				{{ form_errors(form_notes.titre) }}
			</div>
			<div class="col-form">
				{{ form_label(form_notes.contenu) }}
				{{ form_widget(form_notes.contenu, {'attr': {'class': 'tinymce'}}) }}
				{{ form_errors(form_notes.contenu) }}
			</div>
			<button type="submit" class="button-submit btn-sub mb-3">{{ (app.request.get('_route') == 'app_lst_post_it_notes_add' ? 'Créer' : 'Modifier') }}</button>
		</div>
	</div>
	{{ form_end(form_notes) }}
	<script src="{{ asset('js/tinymce.js') }}"></script>
{% endblock %}

templates/pages/post_it_notes/post_it_notes_home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Waou - Post-it & notes
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
{% endblock %}
{% block body %}
	<section class="accueil_post_it_notes element-to-scroll">
		<div class="choice_post_it_or_notes">
			<a href="{{ path('app_lst_calendrier_choses_a_faire') }}">Mes Post-it</a>
			<a href="{{ path('app_post_it_notes_mes_notes') }}">Mes Notes</a>
		</div>
	</section>
	<script src="{{ asset('js/animated-circle.js') }}"></script>
{% endblock %}