src/Entity/Journalier.php
<?php

namespace App\Entity;

use App\Repository\JournalierRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JournalierRepository::class)]
class Journalier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_journalier = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $temps_task = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column]
    private ?bool $statut = null;

    #[ORM\Column]
    private ?bool $affilier = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $id_zoom = null;

    #[ORM\Column(nullable: true)]
    private ?int $id_precis = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lieu_rdv = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $horraire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateJournalier(): ?\DateTimeInterface
    {
        return $this->date_journalier;
    }

    public function setDateJournalier(\DateTimeInterface $date_journalier): static
    {
        $this->date_journalier = $date_journalier;

        return $this;
    }

    public function getTempsTask(): ?\DateTimeInterface
    {
        return $this->temps_task;
    }

    public function setTempsTask(\DateTimeInterface $temps_task): static
    {
        $this->temps_task = $temps_task;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): static
    {
        $this->statut = $statut;

        return $this;
    }
    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function isAffilier(): ?bool
    {
        return $this->affilier;
    }

    public function setAffilier(bool $affilier): static
    {
        $this->affilier = $affilier;

        return $this;
    }

    public function getIdZoom(): ?string
    {
        return $this->id_zoom;
    }

    public function setIdZoom(?string $id_zoom): static
    {
        $this->id_zoom = $id_zoom;

        return $this;
    }

    public function getIdPrecis(): ?int
    {
        return $this->id_precis;
    }

    public function setIdPrecis(?int $id_precis): static
    {
        $this->id_precis = $id_precis;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getLieuRdv(): ?string
    {
        return $this->lieu_rdv;
    }

    public function setLieuRdv(?string $lieu_rdv): static
    {
        $this->lieu_rdv = $lieu_rdv;

        return $this;
    }

    public function getHorraire(): ?\DateTimeInterface
    {
        return $this->horraire;
    }

    public function setHorraire(?\DateTimeInterface $horraire): static
    {
        $this->horraire = $horraire;

        return $this;
    }
}

src/Entity/MesLoisirs.php
<?php

namespace App\Entity;

use App\Repository\MesLoisirsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MesLoisirsRepository::class)]
class MesLoisirs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column(length: 255)]
    private ?string $objet = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $temps_prevue = null;

    #[ORM\Column(length: 255)]
    private ?string $frequence = null;

    #[ORM\Column(nullable: true)]
    private ?int $nombre_action = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $jour_recurrence = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lieu = null;

    #[ORM\Column(length: 255)]
    private ?string $type_loisir = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): static
    {
        $this->objet = $objet;

        return $this;
    }

    public function getTempsPrevue(): ?\DateTimeInterface
    {
        return $this->temps_prevue;
    }

    public function setTempsPrevue(\DateTimeInterface $temps_prevue): static
    {
        $this->temps_prevue = $temps_prevue;

        return $this;
    }

    public function getFrequence(): ?string
    {
        return $this->frequence;
    }

    public function setFrequence(string $frequence): static
    {
        $this->frequence = $frequence;

        return $this;
    }

    public function getNombreAction(): ?int
    {
        return $this->nombre_action;
    }

    public function setNombreAction(?int $nombre_action): static
    {
        $this->nombre_action = $nombre_action;

        return $this;
    }

    public function getJourRecurrence(): ?\DateTimeInterface
    {
        return $this->jour_recurrence;
    }

    public function setJourRecurrence(\DateTimeInterface $jour_recurrence): static
    {
        $this->jour_recurrence = $jour_recurrence;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(?string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getTypeLoisir(): ?string
    {
        return $this->type_loisir;
    }

    public function setTypeLoisir(string $type_loisir): static
    {
        $this->type_loisir = $type_loisir;

        return $this;
    }
}

src/Entity/PlanAction.php
<?php

namespace App\Entity;

use App\Repository\PlanActionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlanActionRepository::class)]
class PlanAction
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column]
    private ?int $id_objectif = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $temps_prevu = null;

    #[ORM\Column(length: 255)]
    private ?string $frequence = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_realisation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $semaine = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getIdObjectif(): ?int
    {
        return $this->id_objectif;
    }

    public function setIdObjectif(int $id_objectif): static
    {
        $this->id_objectif = $id_objectif;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTempsPrevu(): ?\DateTimeInterface
    {
        return $this->temps_prevu;
    }

    public function setTempsPrevu(\DateTimeInterface $temps_prevu): static
    {
        $this->temps_prevu = $temps_prevu;

        return $this;
    }

    public function getFrequence(): ?string
    {
        return $this->frequence;
    }

    public function setFrequence(string $frequence): static
    {
        $this->frequence = $frequence;

        return $this;
    }

    public function getDateRealisation(): ?\DateTimeInterface
    {
        return $this->date_realisation;
    }

    public function setDateRealisation(?\DateTimeInterface $date_realisation): static
    {
        $this->date_realisation = $date_realisation;

        return $this;
    }

    public function getSemaine(): ?string
    {
        return $this->semaine;
    }

    public function setSemaine(?string $semaine): static
    {
        $this->semaine = $semaine;

        return $this;
    }
}

src/Entity/RendezVous.php
<?php

namespace App\Entity;

use App\Repository\RendezVousRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RendezVousRepository::class)]
class RendezVous
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $objet = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_rdv = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $temps_prevu = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lieu_rdv = null;

    #[ORM\Column]
    private ?bool $valide = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column(length: 255)]
    private ?string $frequence = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $horraire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): static
    {
        $this->objet = $objet;

        return $this;
    }

    public function getDateRdv(): ?\DateTimeInterface
    {
        return $this->date_rdv;
    }

    public function setDateRdv(\DateTimeInterface $date_rdv): static
    {
        $this->date_rdv = $date_rdv;

        return $this;
    }

    public function getTempsPrevu(): ?\DateTimeInterface
    {
        return $this->temps_prevu;
    }

    public function setTempsPrevu(\DateTimeInterface $temps_prevu): static
    {
        $this->temps_prevu = $temps_prevu;

        return $this;
    }

    public function getLieuRdv(): ?string
    {
        return $this->lieu_rdv;
    }

    public function setLieuRdv(?string $lieu_rdv): static
    {
        $this->lieu_rdv = $lieu_rdv;

        return $this;
    }

    public function isValide(): ?bool
    {
        return $this->valide;
    }

    public function setValide(bool $valide): static
    {
        $this->valide = $valide;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getFrequence(): ?string
    {
        return $this->frequence;
    }

    public function setFrequence(string $frequence): static
    {
        $this->frequence = $frequence;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getHorraire(): ?\DateTimeInterface
    {
        return $this->horraire;
    }

    public function setHorraire(?\DateTimeInterface $horraire): static
    {
        $this->horraire = $horraire;

        return $this;
    }
}

templates/pages/liste_calendrier/lst_calendrier_choses_a_faire.html.twig
{% extends 'base.html.twig' %}

{% block head %}
	<script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
{% endblock %}

{% block title %}Waou - Liste Petites Choses à faire
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
{% endblock %}
{% block body %}
	<section class="container-list-calendrier element-to-scroll">
		<div class="container-list row">
			<a class="button-add" href="{{ path('app_lst_calendrier_choses_a_faire_add') }}">Ajouter</a>
			<table class="table table-striped">
				<thead>
					<tr class="six_columns">
						<th scope="col" class="intitule" style="width: 30%;">Objet (texte libre)</th>
						<th scope="col">Date Butoir</th>
						<th scope="col">Date Prévue</th>
						<th scope="col">Temps Prévu</th>
						<th scope="col">Action</th>
						<th scope="col">Statut</th>
					</tr>
				</thead>
				<tbody>
					{% for entry in lstCalendrierChosesAFaire %}
						<tr class="six_columns">
							<th scope="row">{{ entry.intitule }}</th>
							<td>{{ entry.dateButoir|date('d-m-Y') }}</td>
							<td class="{% if entry.datePrevue|date('d-m-Y') == dateJour|date('d-m-Y') %}jourJ{% else %}{% endif %}">
								<p>{{ entry.datePrevue|date('d-m-Y') }}</p>
							</td>
							<td>{{ entry.tempsPrevue.format('H:i') }}</td>
							<td>
								<a class="container-relative" href="{{ path('app_valider_choses_a_faire', {'id': entry.id}) }}" onclick="return confirm('Voulez-vous vraiment valider cette petite choses à faire ?')">
									<img style="width: 20%;" src="{{ asset('img/icon-valider-bleu.png') }}">
									<div class="info-bubble">Valider</div>
								</a>
								<a class="container-relative delete-button" href="{{ path('app_lst_calendrier_choses_a_faire_delete', {'id': entry.id}) }}" onclick="return confirm('Voulez-vous vraiment supprimer cette petite choses à faire ?')">
									<img style="width: 30%;" src="{{ asset('img/icon-croix.png') }}" alt="Supprimer">
									<div class="info-bubble">Supprimer</div>
								</a>
								<a class="container-relative" href="{{ path('app_lst_calendrier_choses_a_faire_modify', {'id' : entry.id}) }}">
									<img style="width: 20%;" src="{{ asset('img/icon-modifier.png') }}" alt="modifier">
									<div class="info-bubble">Modifier</div>
								</a>
							</td>
							<td class="container-relative">
								<div style="width: 50px; heigth: 50px; border-radius: 50%; text-align: center; font-size: 1.5rem;" class="{% if entry.valide %}case-verte{% else %}case-rouge{% endif %}">-</div>
								<div class="info-bubble">
									{% if entry.valide %}
										Fait le
										{{ entry.faitLe|date('d/m/Y') }}
									{% else %}
										A faire
									{% endif %}
								</div>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</section>
{% endblock %}

templates/pages/liste_calendrier/lst_calendrier_choses_a_faire_add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Waou -
	{{ (app.request.get('_route') == 'app_lst_calendrier_choses_a_faire_add' ? 'Ajouter' : 'Modifier') }}
	une Choses A Faire
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
	{{ encore_entry_link_tags('login') }}
{% endblock %}
{% block body %}
	{{ form_start(form_calendrier_choses_a_faire, {'attr': {'class': 'element-to-scroll mb-5'}}) }}
	<div class="row container-principal-form">
		<div class="col-8 mx-auto container-intro">
			<div class="col-form" style="width: 100%;">
				<h1>{{ (app.request.get('_route') == 'app_lst_calendrier_choses_a_faire_add' ? 'Créer' : 'Modifier') }}
					un Rappel</h1>
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_choses_a_faire.intitule) }}
				{{ form_widget(form_calendrier_choses_a_faire.intitule) }}
				{{ form_errors(form_calendrier_choses_a_faire.intitule) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_choses_a_faire.date_butoir) }}
				{{ form_widget(form_calendrier_choses_a_faire.date_butoir) }}
				{{ form_errors(form_calendrier_choses_a_faire.date_butoir) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_choses_a_faire.date_prevue) }}
				{{ form_widget(form_calendrier_choses_a_faire.date_prevue) }}
				{{ form_errors(form_calendrier_choses_a_faire.date_prevue) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_choses_a_faire.temps_prevue) }}
				{{ form_widget(form_calendrier_choses_a_faire.temps_prevue) }}
				{{ form_errors(form_calendrier_choses_a_faire.temps_prevue) }}
			</div>
			<button type="submit" class="button-submit btn-sub mb-3">{{ (app.request.get('_route') == 'app_lst_calendrier_choses_a_faire_add' ? 'Créer' : 'Modifier') }}</button>
		</div>
	</div>
	{{ form_end(form_calendrier_choses_a_faire) }}
{% endblock %}

templates/pages/liste_calendrier/lst_calendrier_evenement.html.twig
{% extends 'base.html.twig' %}

{% block head %}
	<script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
{% endblock %}

{% block title %}Waou - Liste Évenement à Souhaiter
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
{% endblock %}
{% block body %}
	<section class="container-list-calendrier element-to-scroll">
		<div class="container-list row">
			<a class="button-add" href="{{ path('app_lst_calendrier_evenement_add') }}">Ajouter</a>
			<table class="table table-striped">
				<thead>
					<tr class="four-columns">
						<th scope="col">Événements</th>
						<th scope="col">Date</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
					{% for entry in lstCalendrierEvenement %}
						<tr class="four-columns">
							<th scope="row">{{ entry.evenement }}</th>
							<td>{{ entry.jourEvenement|date('d-m-Y') }}</td>
							<td>
								<a class="container-relative" href="{{ path('app_valider_evenement', {'id': entry.id}) }}" onclick="return confirm('Voulez-vous vraiment valider cet evenement ?')">
									<img style="width: 8%;" src="{{ asset('img/icon-valider-bleu.png') }}">
									<div class="info-bubble">Valider</div>
								</a>
								<a class="container-relative delete-button" href="{{ path('app_lst_calendrier_evenement_delete', {'id': entry.id}) }}" onclick="return confirm('Voulez-vous vraiment supprimer cet evenement ?')">
									<img src="{{ asset('img/icon-croix.png') }}" alt="Supprimer">
									<div class="info-bubble">Supprimer</div>
								</a>
								<a class="container-relative" href="{{ path('app_lst_calendrier_evenement_modify', {'id' : entry.id}) }}">
									<img style="width: 10%;" src="{{ asset('img/icon-modifier.png') }}" alt="modifier">
									<div class="info-bubble">Modifier</div>
								</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</section>
{% endblock %}

templates/pages/liste_calendrier/lst_calendrier_evenement_add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Waou -
	{{ (app.request.get('_route') == 'app_lst_calendrier_evenement_add' ? 'Créer' : 'Modifier') }}
	un Événement à  Souhaiter
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
	{{ encore_entry_link_tags('login') }}
{% endblock %}
{% block body %}
	{{ form_start(form_calendrier_evenement, {'attr': {'class': 'element-to-scroll mb-5'}}) }}
	<div class="row container-principal-form">
		<div class="col-8 mx-auto container-intro">
			<div class="col-form" style="width: 100%;">
				<h1>{{ (app.request.get('_route') == 'app_lst_calendrier_evenement_add' ? 'Créer' : 'Modifier') }}
					un Rappel</h1>
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_evenement.evenement) }}
				{{ form_widget(form_calendrier_evenement.evenement) }}
				{{ form_errors(form_calendrier_evenement.evenement) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_evenement.jour_evenement) }}
				{{ form_widget(form_calendrier_evenement.jour_evenement) }}
				{{ form_errors(form_calendrier_evenement.jour_evenement) }}
			</div>
			<button type="submit" class="button-submit btn-sub mb-3">{{ (app.request.get('_route') == 'app_lst_calendrier_evenement_add' ? 'Créer' : 'Modifier') }}</button>
		</div>
	</div>
	{{ form_end(form_calendrier_evenement) }}
{% endblock %}

templates/pages/liste_calendrier/lst_calendrier_rdv_add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Waou -
	{{ (app.request.get('_route') == 'app_lst_calendrier_rdv_add' ? 'Créer' : 'Modifier') }}
	un Rendez-vous à prendre
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
	{{ encore_entry_link_tags('login') }}
{% endblock %}
{% block body %}
	{{ form_start(form_calendrier_rdv, {'attr': {'class': 'element-to-scroll mb-5'}}) }}
	<div class="row container-principal-form">
		<div class="col-8 mx-auto container-intro">
			<div class="col-form" style="width: 100%;">
				<h1>{{ (app.request.get('_route') == 'app_lst_calendrier_rdv_add' ? 'Créer' : 'Modifier') }}
					un Rendez-Vous</h1>
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_rdv.objet) }}
				{{ form_widget(form_calendrier_rdv.objet) }}
				{{ form_errors(form_calendrier_rdv.objet) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_rdv.date_rdv) }}
				{{ form_widget(form_calendrier_rdv.date_rdv) }}
				{{ form_errors(form_calendrier_rdv.date_rdv) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_rdv.temps_prevu) }}
				{{ form_widget(form_calendrier_rdv.temps_prevu) }}
				{{ form_errors(form_calendrier_rdv.temps_prevu) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_rdv.telephone) }}
				{{ form_widget(form_calendrier_rdv.telephone) }}
				{{ form_errors(form_calendrier_rdv.telephone) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_rdv.horraire) }}
				{{ form_widget(form_calendrier_rdv.horraire) }}
				{{ form_errors(form_calendrier_rdv.horraire) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_rdv.lieu_rdv) }}
				{{ form_widget(form_calendrier_rdv.lieu_rdv) }}
				{{ form_errors(form_calendrier_rdv.lieu_rdv) }}
			</div>
			<div class="col-form">
				{{ form_label(form_calendrier_rdv.frequence) }}
				{{ form_widget(form_calendrier_rdv.frequence) }}
				{{ form_errors(form_calendrier_rdv.frequence) }}
			</div>
			<button type="submit" class="button-submit btn-sub mb-3">{{ (app.request.get('_route') == 'app_lst_calendrier_rdv_add' ? 'Créer' : 'Modifier') }}</button>
		</div>
	</div>
	{{ form_end(form_calendrier_rdv) }}
{% endblock %}

templates/pages/liste_calendrier/lst_calendrier_rendez_vous.html.twig
{% extends 'base.html.twig' %}

{% block title %}Waou - Liste des rendez-vous à prendre
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('list_calendrier') }}
{% endblock %}
{% block body %}
	<section class="container-list-calendrier element-to-scroll">
		<div class="container-list row">
			<a class="button-add" href="{{ path('app_lst_calendrier_rdv_add') }}">Ajouter</a>
			<table class="table table-striped">
				<thead>
					<tr class="six_columns">
						<th scope="col" style="width: 30%;">Objet (texte libre)</th>
						<th scope="col">Date du RDV</th>
						<th scope="col">Temps prévu</th>
						<th scope="col">Lieu du rdv</th>
						<th scope="col">Action</th>
						<th scope="col">statut</th>
					</tr>
				</thead>
				<tbody>
					{% for entry in lstRendezVous %}
						<tr class="six_columns">
							<th scope="row">{{ entry.objet }}</th>
							<td>{{ entry.dateRdv|date('d-m-Y') }}</td>
							<td>{{ entry.tempsPrevu.format('H:i') }}</td>
							<td>{{ entry.lieuRdv }}</td>
							<td>
								<a class="container-relative" href="{{ path('app_rendez_vous_valide', {'id': entry.id}) }}" onclick="return confirm('Voulez-vous vraiment valider cet evenement ?')">
									<img style="width: 20%;" src="{{ asset('img/icon-valider-bleu.png') }}">
									<div class="info-bubble">Valider</div>
								</a>
								<a class="container-relative delete-button" href="{{ path('app_lst_calendrier_rdv_delete', {'id': entry.id}) }}" onclick="return confirm('Voulez-vous vraiment supprimer cet evenement ?')">
									<img style="width: 30%;" src="{{ asset('img/icon-croix.png') }}" alt="Supprimer">
									<div class="info-bubble">Supprimer</div>
								</a>
								<a class="container-relative" href="{{ path('app_lst_calendrier_rdv_modify', {'id' : entry.id}) }}">
									<img style="width: 23%;" src="{{ asset('img/icon-modifier.png') }}" alt="modifier">
									<div class="info-bubble">Modifier</div>
								</a>
							</td>
							<td class="container-relative">
								<div style="width: 50px; heigth: 50px; border-radius: 50%; text-align: center; font-size: 1.5rem;" class="{% if entry.valide %}case-verte{% else %}case-rouge{% endif %}">-</div>
								<div class="info-bubble">
									{% if entry.valide %}
										Fait
									{% else %}
										A faire
									{% endif %}
								</div>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</section>
{% endblock %}